const PUBLIC_VAPID_KEY = "BMfd76O0cdcOIp2b2SYtvq7pTkG7u-gL-ohAYFwTasksMm2uN1rXAsuFGqBN9mhpjxiO7pRf3htYH313iTSSykE"
const PRIVATE_VAPID_KEY = "FE_lhsKJ3xbQjyjs3I5Fp7tbVQO0B0qtr2pY1UX9Bzw"

const VAPID_KEYS = {
  PUBLIC_VAPID_KEY : PUBLIC_VAPID_KEY,
  PRIVATE_VAPID_KEY : PRIVATE_VAPID_KEY
}

module.exports = VAPID_KEYS